<?php
/**
 * GEMBOK Configuration File
 * Generated by installer on: 2026-03-03 22:38:12
 */

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'gembok_simple2');
define('DB_USER', 'root');
define('DB_PASS', '');

// MikroTik Configuration
define('MIKROTIK_HOST', '192.168.8.1');
define('MIKROTIK_USER', 'alijaya');
define('MIKROTIK_PASS', '060111');
define('MIKROTIK_PORT', 8700);

// Application Configuration
define('APP_NAME', 'GEMBOK');
if (php_sapi_name() !== 'cli' && isset($_SERVER['HTTP_HOST'])) {
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $scriptDir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME']));
    $scriptDir = preg_replace('#/(admin|api|portal|cron|webhooks|install_steps|includes|sales|templates|technician)$#', '', $scriptDir);
    $scriptDir = rtrim($scriptDir, '/');
    define('APP_URL', $protocol . '://' . $_SERVER['HTTP_HOST'] . $scriptDir);
} else {
    define('APP_URL', 'http://localhost');
}
define('APP_VERSION', '2.0.6');
define('GEMBOK_UPDATE_VERSION_URL', 'https://raw.githubusercontent.com/alijayanet/gembok-simple/main/version.txt');

// Pagination
define('ITEMS_PER_PAGE', 20);
define('INVOICE_PREFIX', 'INV');
define('INVOICE_START', 1);

// Security
define('ENCRYPTION_KEY', '5ab34f95a6018ea5dfb7c55c7ab3c76bc187f559a133147bc2d1f8a529a39484');

// WhatsApp Configuration
define('WHATSAPP_API_URL', '');
define('WHATSAPP_TOKEN', '');

// Tripay Configuration
define('TRIPAY_API_KEY', '');
define('TRIPAY_PRIVATE_KEY', '');
define('TRIPAY_MERCHANT_CODE', '');

// Telegram Configuration
define('TELEGRAM_BOT_TOKEN', '');

// GenieACS Configuration
define('GENIEACS_URL', 'http://localhost:7557');
define('GENIEACS_USERNAME', '');
define('GENIEACS_PASSWORD', '');